#
# songmap.coffee
#
# Provides a map of song from DJMAX TECHNIKA's internal song ID to a readable song ID.
#


module.exports =
	'@naege': 'Come To Me'
	'@youngwon': 'Forever'
	'thor': 'Thor'
	'ladymade': 'Ladymade Star'
	'oblivion': 'Oblivion'
	'cherokee': 'Cherokee'
	'dreamofwinds': 'Dream of Winds'
	'cypher': 'Cypher Gate'
	'd2': 'D2'
	'whiteblue': 'Whiteblue'
	'supersonicrmx': 'Supersonic RMX'
	'rage': 'Rage of Demon'
	'fermion': 'Fermion'
	'sweetdream': 'Sweet Dream'
	'beeutiful': 'BEE-U-TIFUL'
	'thenightstage': 'The Night Stage'
	'outlawreborn': 'Out Law -Reborn-'
	'enemystorm': 'Enemy Storm'
	'airwave': 'Airwave'
	'zetrmx1': 'Zet RMX'
	'divineservice': 'Divine Service'
	'sin': 'SIN'
	'blythe': 'BlythE'
	'pdm': 'PDM'
	'firstkiss': 'First Kiss'
	'putemup': 'Put Em Up'
	'@gobaek1': 'PFW'
	'@gobaek2': 'PFW2'
	'heartofwitch': 'Heart of Witch'
	'brandnewdays': 'Brand New Days'
	'@baramegelive': 'Ask The Wind Live'
	'@ner': 'To You'
	'@piano': 'Piano Concerto No.1'
	'@baramege': 'Ask The Wind'
	'iwantyou': 'I Want You'
	'someday': 'Someday'
	'cosmicfantastic': 'Cosmic Fantastic'
	'endofthemoon': 'End of the Moonlight'
	'oblivion': 'Oblivion'
	'djmax': 'DJMAX'
	'flea': 'Flea'
	'eternalmemory': 'Eternal Memory'
	'desperadormx1': 'Desperado RMX'
	'inmyheart': 'In My Heart'
	'luvflowrmx1': 'Luv Flow RMX'
	'color': 'Color'
	'secretworld': 'Secret World'
	'cozyquilt': 'Cozy Quilt'
	'rayof': 'Ray of Illuminati'
	'thelastdance': 'The Last Dance'
	'eternalfantasy': 'Eternal Fantasy'
	'loveis': 'Love is Beautiful'
	'spaceofsoul': 'Space of Soul'
	'coloursof': 'Colours of Sorrow'
	'theclear': 'The Clear Blue Sky'
	'dualstrikers': 'Dual Strikers'
	'coastaltempo': 'Coastal Tempo'
	'beyondthe': 'Beyond the Future'
	'closer': 'Closer'
	'freedom': 'Freedom'
	'honeymoon': 'Honeymoon'
	'sweetshining': 'SSSS'
	'sayitfrom': 'Say It From Your Heart'
	'beatudown': 'Beat U Down'
	'grave': 'Grave Consequence'
	'showline': 'Shoreline'
	'novarmx': 'Nova RMX'
	'sonof': 'Son Of Sun'
	'miles': 'Miles'
	'hexad': 'HEXAD'
	'fate': 'Fate'
	'enemyrmx1': 'Enemy Storm RMX'
	'access': 'Access'
	'yourown': 'Your Own Miracle'
	'lovemode': 'Love Mode'
	'playthefuture': 'Play The Future'
	'jupiter': 'Jupiter Driving'
	'xlasher': 'Xlasher'
	'masairmx1': 'Masai RMX'
	'keystothe': 'Keys to the World'
	'area7': 'Area 7'
	'burnitdown': 'Burn It Down'
	'monoxide': 'MonoXide'
	'getdown': 'Get Down'
	'theguilty': 'The Guilty'

